#!/bin/bash

# Make recyclebin directory
mkdir -p $HOME/recyclebin

interactive=0
verbose=0
recursive=0

# Parse option flags
while getopts "irv" option; do
    case $option in
        i) interactive=1 ;;
        r) recursive=1 ;;
        v) verbose=1 ;;
        *) echo "Invalid option"; exit 1 ;;
    esac~
done
shift $((OPTIND -1))

# Check if at least one file is provided
if [ $# -eq 0 ]; then
    echo "No files provided."
    exit 1
fi

recycle_file() {
    local file="$1"

    if [ ! -e "$file" ]; then
        echo "File '$file' does not exist."
        return
    fi

    # Check if argument is 'recycle'
    if [ "$(basename "$file")" = "recycle" ]; then
	    echo "Attempting to delete recycle -- operation aborted."
	    exit 1
    fi

    if [ $interactive -eq 1 ]; then
        read -p "Are you sure you want to delete '$file'? (y/n): " response < /dev/tty
        if [[ ! $response =~ ^[Yy] ]]; then
            echo "Skipping '$file'."
            return
        fi
    fi

    # Generate a unique file name with inode (filename_inode)
    inode=$(stat --format="%i" "$file")
    filename=$(basename "$file")
    name_inode="${filename}_${inode}"
    original_path=$(realpath "$file")

    mv "$file" "$HOME/recyclebin/$name_inode"

    echo "$name_inode:$original_path" >> "$HOME/.restore.info"
    
    if [ $verbose -eq 1 ]; then
        echo "Recycled '$file'"
    fi
}

recycle_directory() {
    local dir="$1"

    # Check if directory exists
    if [ ! -e "$dir" ]; then
        echo "Directory '$dir' does not exist."
        return
    fi

    # Check if argument is 'recycle'
    if [ "$dir" == "recycle" ]; then
	    echo "Attempting to delete recycle -- operation aborted."
	    return
    fi

    if [ $recursive -eq 0 ]; then
        echo "'$dir' is a directory. Use -r option to delete directories."
        return
    fi

    # Recycle all files in the directory
    while IFS= read -r -d '' f; do
        recycle_file "$f"
    done < <(find "$dir" -type f -print0 2>/dev/null)

    # Keep non-empty directories
    if find "$dir" -type f 2>/dev/null | grep -q .; then
        [ $verbose -eq 1 ] && echo "kept directory '$dir' (still contains files)"
        return
    fi

    # Remove empty directories
    find  "$dir" -type d -depth -exec rmdir {} \; 2>/dev/null

    rm -r "$dir" 2>/dev/null
    [ $verbose -eq 1 ] && echo "Removed empty directory '$dir'"
}


#Go through the provided arguments
for item in "$@"; do
    if [ -d "$item" ]; then
        recycle_directory "$item"
    else
        recycle_file "$item"
    fi
done

